# Generated by Django 3.2.4 on 2023-08-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_man', '0071_update_ap_gse_version_to_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginconfigtemplate',
            name='variables',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='配置变量'),
        ),
    ]
